repos:
  - repo: https://github.com/mercadolibre/fury_websec-git-hooks
    rev: v1.0.5
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]
  - repo: https://github.com/mercadolibre/fury_datasec-git-hooks
    rev: 1.0.1
    hooks:
      - id: pre_commit_hook
        stages: [commit]
        verbose: true
